application: pagepusher
version: 1
runtime: python27
threadsafe: no
api_version: 1

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

inbound_services:
- mail

handlers:
- url: /static/
  static_dir: static
- url: /_ah/mail/.+ 
  script: in_mail.py
- url: /m.*
  script: messagehandler.py
  login: required
  auth_fail_action: unauthorized
- url: /admin
  script: admin.py
  login: admin
- url: .*
  script: main.py
